language: c
jobs:
   include:
      - script: make
      - script: rm ofile; ./hellomake.exe > ofile
notifications:
  email:
    recipients:
        - chrispthompson@gmail.com
    on_success: always
    on_failure: always
