language: c
notifications:
  email:
    recipients:
        - chrispthompson@gmail.com
    on_success: always
    on_failure: always
env:
   before_install:
   - export TRAVIS_ROOT=$HOME/travis
   - mkdir -p $TRAVIS_ROOT
   install:
   - make hellomake
   script:
   - ./hellomake.exe
jobs:
   include:
      - script: make
      - script: ./hellomake.exe 
   cache:
     apt: true
     directories:
     - $HOME/travis
