addons:
  apt:
    packages:
    - gfortran
language: c
notifications:
  #email:
    #recipients: Maybe we can have email OR slack, but not both!
       # - chrispthompson@gmail.com
 #notifications:
    slack: ibm-uk-labs:42MJmUKnRLBKZXzfz3sK5XKy
    template: #Doesn't seem to do anything! Does it only work for irc?
      - "%{repository_slug} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"
      - "Result: %{result}"
    on_success: always
    on_failure: always
compiler:
    -gcc
    -clang
    -gfortran
script:
    - make && ./hellomakeic.exe > oofile
    - pwd
    - cat oofile
    - make hellomakef && ./hellomakef.exe
