language: c
jobs:
   include:
      - script: make
      - script: ./hellomake.exe
notifications:
  email:
    recipients:
        - chrispthompson@gmail.com
    on_success: always
    on_failure: always
