language: c
notifications:
  email:
    recipients:
        - chrispthompson@gmail.com
    template: #Doesn't seem to do anything! Does it only work for irc?
      - "%{repository_slug} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"
      - "Result: %{result}"
    on_success: always
    on_failure: always
compiler:
    -gcc
script:
    - make && ./hellomake.exe > oofile
    - pwd
    - cat oofile
