addons:
  apt:
    packages:
    - gfortran
language: c
notifications:
  email:
    recipients:
        - chrispthompson@gmail.com
 #notifications:
    #slack: ibm-uk-labs:token??
    #template: #Doesn't seem to do anything! Does it only work for irc?
    #  - "%{repository_slug} (%{commit}) : %{message} %{foo} "
    #  - "Build details: %{build_url}"
    #  - "Result: %{result}"
    on_success: always
    on_failure: always
compiler:
    -gcc
    -clang
    -gfortran
script:
    - make hellomakec && ./hellomakec.exe > oofile
    - pwd
    - cat oofile
    # look at https://gist.github.com/willprice/e07efd73fb7f13f917ea
    - make hellomakef && ./hellomakef.exe
    - uname -a
    - echo "End of script"
#after_success: # Does this work?
    - echo "After SUCCESS"
    - uname -a
    - .travis/push.sh
