addons:
  apt:
    packages:
    - gfortran
language: c
notifications:
  #email:
    #recipients: Maybe we can have email OR slack, but not both!
       # - chrispthompson@gmail.com
 #notifications:
    #slack: ibm-uk-labs:token??
    #template: #Doesn't seem to do anything! Does it only work for irc?
    #  - "%{repository_slug} (%{commit}) : %{message} %{foo} "
    #  - "Build details: %{build_url}"
    #  - "Result: %{result}"
    on_success: always
    on_failure: always
compiler:
    -gcc
    -clang
    -gfortran
script:
    - make hellomakec && ./hellomakec.exe > oofile
    - pwd
    - cat oofile
    # look at https://gist.github.com/willprice/e07efd73fb7f13f917ea
    - git status
    - git add .
    - git commit -a -message="From Travis-ci"
    - git status
    - git push --branch=master https://github.com/mm002a/Fort-C.git mm002a/Fort-C
    - make hellomakef && ./hellomakef.exe
