language: c
notifications:
  email:
    recipients:
        - chrispthompson@gmail.com
    template:
      - "%{repository_slug} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"
      - "Result: %{result}"
    on_success: always
    on_failure: always
compiler:
    -gcc
script:
    - make && ./hellomake.exe
    - pwd
