#!/bin/bash -v
uname -a
#echo (( `uname` == Darwin ))
#if [  -e .travis ] ;
#if [ `uname` == "Darwin" ] ;
if [ `/usr/bin/whoami` == "ChristopherThompson" ] ;
then
 echo LOOKS LIKE Darwin
else 
 echo ELSE CLAUSE
 exit
fi
echo AFTER IF
exit
echo AFTER EXIT # Shouldn't ever see this!
